### ISSUE TITLE
Org Membership Access

### ISSUE THREAD

**Issue by dashtangui** [mindersec/community#5]
I would like to request membership to mindersec.

**Comment by evankanderson** [comment]
In particular, Dania is an engineering manager at Stacklok.  Along with several other folks, she helps to organize issue management (triage, sprints, etc).

I believe that Dania (and possibly others at Stacklok and future contributing companies) are looking for the `write` permission on issues, but are not looking for permissions to create repos or to approve code reviews.  In the future, this could include things like "technical program manager supporting Minder at $COMPANY".

This will probably require a governance vote to establish a consistent policy, rather than just doing a series of one-off decisions.

**Comment by evankanderson** [comment]
One possible solution:

1. Create a `.github/CODEOWNERS` in each repo (e.g. using a Minder policy) which grants
   ```
   * @mindersec/maintainers
   ```
1. Create a repository rule (or branch protection rule) which turns on "require CODEOWNERS approval".  Again, this could be a Minder policy.
2. The above two combined should limit approving reviews to members of `@mindersec/maintainers`.
3. Permit org membership to anyone who has meaningfully participated in the community in some way: issue management, community organizing, etc, regardless of PR contributions.
4. Grant `write` permissions to all org members.  Given the branch / code review protections from (1) and (2), this should grant access to manage (close, etc) other people's issues (and to re-run actions, etc), but not impact the security of the `mindersec` org.

**Comment by evankanderson** [comment]
@mindersec/maintainers -- I'll be doing a poll tomorrow on the above solution; if we approve (e.g. via non-binding 👍  reactions on [this comment](https://github.com/mindersec/community/issues/5#issuecomment-2415304930), I'll create PRs to document and enforce the policy above.

**Comment by mesembria** [comment]
I would like to request membership to mindersec, as well. I'm one of the other folks that deals with issue management.
